# BMad YOLO Configuration
version: 1.0.0

# YOLO Mode Settings
yolo:
  enabled: false
  auto_approve: true
  skip_confirmations: true
  use_defaults: true
  max_consecutive_errors: 3
  safety_stop_on_critical: true

# Default Decisions
defaults:
  technical:
    language: python
    framework: fastapi
    frontend: nextjs
    database: postgresql
    testing: pytest
    ci_cd: github_actions
    containerization: docker
    
  process:
    epic_count: 3
    stories_per_epic: 4
    test_coverage_target: 80
    code_review_required: true
    auto_merge_on_pass: true
    
  workflow:
    on_success: proceed_to_next
    on_minor_issues: document_and_continue
    on_major_issues: pause_and_alert
    on_critical_error: stop_and_rollback

# Agent Configurations
agents:
  pm:
    auto_decisions:
      - create_prd
      - define_epics
      - set_priorities
    handoff_to: architect
    
  architect:
    auto_decisions:
      - design_architecture
      - choose_tech_stack
      - define_patterns
    handoff_to: po
    
  po:
    auto_decisions:
      - shard_documents
      - create_epics
      - prioritize_backlog
    handoff_to: sm
    
  sm:
    auto_decisions:
      - create_stories
      - assign_points
      - set_sprint
    handoff_to: dev
    
  dev:
    auto_decisions:
      - implement_story
      - write_tests
      - update_docs
    handoff_to: qa
    
  qa:
    auto_decisions:
      - run_tests
      - validate_requirements
      - make_gate_decision
    handoff_to: sm

# Safety Mechanisms
safety:
  stop_keywords:
    - delete
    - drop
    - remove
    - destroy
    - payment
    - billing
    - credential
    - password
    - production
    - deploy
    
  require_confirmation:
    - database_migration
    - api_changes
    - security_updates
    - production_deployment
    
  max_auto_decisions: 100
  decision_timeout_minutes: 60

# Workflow Phases
workflow:
  phases:
    - planning
    - architecture
    - story_creation
    - development
    - testing
    - review
    - deployment
    - complete
    
  transitions:
    planning: architecture
    architecture: story_creation
    story_creation: development
    development: testing
    testing: review
    review: deployment
    deployment: complete

# Logging
logging:
  level: INFO
  file: yolo.log
  max_size_mb: 100
  rotation_count: 5
  
# Monitoring
monitoring:
  health_check_interval: 30
  metrics_enabled: true
  alert_on_errors: true
  slack_webhook: null
