apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ruleiq-frontend
  labels:
    cloud.googleapis.com/location: europe-west2
spec:
  template:
    metadata:
      annotations:
        # Maximum number of concurrent requests per container instance
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
        autoscaling.knative.dev/maxScale: '100'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ruleiq-frontend-sa@ruleiq.iam.gserviceaccount.com
      containers:
        - image: gcr.io/ruleiq/ruleiq-frontend:latest
          name: ruleiq-frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: NEXT_TELEMETRY_DISABLED
              value: '1'
            # API Configuration
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_API_URL
                  key: latest
            - name: NEXT_PUBLIC_WEBSOCKET_URL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_WEBSOCKET_URL
                  key: latest
            # Application URLs
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_APP_URL
                  key: latest
            - name: NEXT_PUBLIC_HELP_URL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_HELP_URL
                  key: latest
                  optional: true
            - name: NEXT_PUBLIC_DOCS_URL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_DOCS_URL
                  key: latest
                  optional: true
            # Authentication
            - name: NEXT_PUBLIC_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_AUTH_DOMAIN
                  key: latest
            - name: NEXT_PUBLIC_JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_JWT_EXPIRES_IN
                  key: latest
                  optional: true
            # Email Configuration
            - name: NEXT_PUBLIC_SUPPORT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_SUPPORT_EMAIL
                  key: latest
                  optional: true
            - name: NEXT_PUBLIC_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_ADMIN_EMAIL
                  key: latest
                  optional: true
            - name: NEXT_PUBLIC_CONTACT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_CONTACT_EMAIL
                  key: latest
                  optional: true
            # Feature Flags
            - name: NEXT_PUBLIC_ENABLE_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_ENABLE_ANALYTICS
                  key: latest
                  optional: true
            - name: NEXT_PUBLIC_ENABLE_SENTRY
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_ENABLE_SENTRY
                  key: latest
                  optional: true
            - name: NEXT_PUBLIC_ENABLE_MOCK_DATA
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_ENABLE_MOCK_DATA
                  key: latest
                  optional: true
            # External Services
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: SENTRY_DSN
                  key: latest
                  optional: true
            - name: SENTRY_ORG
              valueFrom:
                secretKeyRef:
                  name: SENTRY_ORG
                  key: latest
                  optional: true
            - name: SENTRY_PROJECT
              valueFrom:
                secretKeyRef:
                  name: SENTRY_PROJECT
                  key: latest
                  optional: true
            - name: SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: SENTRY_AUTH_TOKEN
                  key: latest
                  optional: true
            # Analytics
            - name: NEXT_PUBLIC_VERCEL_ANALYTICS_ID
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_VERCEL_ANALYTICS_ID
                  key: latest
                  optional: true
            # Payment (Stripe)
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
                  key: latest
                  optional: true
            # Environment
            - name: NEXT_PUBLIC_ENV
              value: production
          resources:
            requests:
              cpu: '0.5'
              memory: 512Mi
            limits:
              cpu: '1'
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
              httpHeaders:
                - name: User-Agent
                  value: GoogleHC/1.0
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true