# SonarCloud Configuration
# This file is automatically maintained - manual changes may be overwritten

# Pull Request Decoration
sonar.pullrequest.provider=GitHub
sonar.pullrequest.github.repository=omara1-bakri/ruleIQ
sonar.pullrequest.github.endpoint=https://api.github.com/

# Quality Gate Configuration
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

# Analysis Parameters
sonar.analysis.mode=publish
sonar.verbose=false
sonar.log.level=INFO

# Coverage Gates
sonar.coverage.exclusions=\
  **/test_*.py,\
  **/*_test.py,\
  **/tests/**,\
  **/conftest.py,\
  **/migrations/**,\
  **/alembic/**,\
  **/historical/**,\
  **/backups/**,\
  **/__pycache__/**

# Duplication Detection
sonar.cpd.python.minimumTokens=100
sonar.cpd.python.minimumLines=10

# Complexity Thresholds
sonar.python.cognitive.complexity.threshold=15
sonar.python.file.complexity.threshold=200
sonar.python.function.complexity.threshold=10

# Code Smell Thresholds
sonar.issue.ignore.multicriteria=e1,e2,e3

# Ignore specific rules for legacy code (temporary)
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S107
sonar.issue.ignore.multicriteria.e1.resourceKey=**/historical/**

sonar.issue.ignore.multicriteria.e2.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/migrations/**

sonar.issue.ignore.multicriteria.e3.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=**/test_*.py

# Branch Analysis
sonar.branch.autoconfig.disabled=false
sonar.branch.name=${GITHUB_REF_NAME}
sonar.branch.target=main

# Security Hotspot Review
sonar.security.hotspots.review.enabled=true
sonar.security.hotspots.max-issues=100