# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ruleiq-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ruleiq-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/ruleiq-backend'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ruleiq-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ruleiq-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--execution-environment'
      - 'gen2'
      - '--startup-cpu-boost'
      - '--concurrency'
      - '80'
      - '--cpu-throttling'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,PORT=8080,ENVIRONMENT=production'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,GOOGLE_AI_API_KEY=GOOGLE_AI_API_KEY:latest,REDIS_URL=REDIS_URL:latest'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ruleiq-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ruleiq-backend:latest'

# Timeout for the entire build
timeout: '1200s'

# Service account to use for the build
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cloud-build@$PROJECT_ID.iam.gserviceaccount.com'

# Build logs bucket
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'