#!/bin/bash

# Script to help fix PostgreSQL authentication issues

echo "===================================="
echo "PostgreSQL Authentication Fix Helper"
echo "===================================="
echo ""
echo "This script will guide you through fixing the PostgreSQL authentication issue."
echo ""
echo "The error indicates that the password 'password' is incorrect for the postgres user."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. First, try connecting with your system user (peer authentication):"
echo "   $ sudo -u postgres psql"
echo ""
echo "2. Once connected, set a new password for the postgres user:"
echo "   postgres=# ALTER USER postgres PASSWORD 'your_new_password';"
echo "   postgres=# \q"
echo ""
echo "3. Update the DATABASE_URL in your .env file with the new password:"
echo "   DATABASE_URL=postgresql://postgres:your_new_password@localhost:5432/ruleiq_test"
echo ""
echo "4. Make sure your pg_hba.conf file allows password authentication."
echo "   The file is usually located at: /etc/postgresql/*/main/pg_hba.conf"
echo "   Ensure this line exists:"
echo "   local   all             postgres                                md5"
echo "   host    all             all             127.0.0.1/32            md5"
echo ""
echo "5. After making changes to pg_hba.conf, restart PostgreSQL:"
echo "   $ sudo systemctl restart postgresql"
echo ""
echo "Alternative: Use trust authentication (less secure, for development only):"
echo "1. Edit pg_hba.conf and change 'md5' to 'trust' for local connections"
echo "2. This allows connection without password"
echo "3. Update .env file: DATABASE_URL=postgresql://postgres@localhost:5432/ruleiq_test"
echo ""
echo "For immediate testing without changing PostgreSQL config:"
echo "You can create a new PostgreSQL user with a known password:"
echo "$ sudo -u postgres createuser --interactive --pwprompt ruleiq_user"
echo "$ sudo -u postgres createdb -O ruleiq_user ruleiq_test"
echo "Then update DATABASE_URL=postgresql://ruleiq_user:your_password@localhost:5432/ruleiq_test"