#!/bin/bash
# Setup test environment with Doppler secrets

echo "🔧 Setting up test environment with Doppler..."

# Check if Doppler is installed
if ! command -v doppler &> /dev/null; then
    echo "❌ Doppler CLI not found. Please install it first:"
    echo "   curl -Ls https://cli.doppler.com/install.sh | sh"
    exit 1
fi

# Check if logged in to Doppler
if ! doppler configs &> /dev/null; then
    echo "❌ Not logged in to Doppler. Please run: doppler login"
    exit 1
fi

# Set the Doppler config for tests
export DOPPLER_CONFIG="dev"
echo "✅ Using Doppler config: $DOPPLER_CONFIG"

# Export test-specific environment variables
echo "📦 Loading test secrets from Doppler..."

# Get test database URL
export TEST_DATABASE_URL=$(doppler secrets get TEST_DATABASE_URL --plain 2>/dev/null)
if [ -z "$TEST_DATABASE_URL" ]; then
    echo "⚠️  TEST_DATABASE_URL not found in Doppler, using DATABASE_URL"
    export TEST_DATABASE_URL=$(doppler secrets get DATABASE_URL --plain)
fi

# Get Redis URL
export REDIS_URL=$(doppler secrets get REDIS_URL --plain 2>/dev/null)
if [ -z "$REDIS_URL" ]; then
    echo "⚠️  REDIS_URL not found, using default: redis://localhost:6379"
    export REDIS_URL="redis://localhost:6379"
fi

# Get other critical test variables
export JWT_SECRET_KEY=$(doppler secrets get JWT_SECRET_KEY --plain 2>/dev/null)
export OPENAI_API_KEY=$(doppler secrets get OPENAI_API_KEY --plain 2>/dev/null)
export ANTHROPIC_API_KEY=$(doppler secrets get ANTHROPIC_API_KEY --plain 2>/dev/null)

# Create a temporary .env.test file for pytest-dotenv plugin
echo "📝 Creating temporary .env.test file..."
cat > .env.test << EOF
# Temporary test environment file (generated by setup_test_env.sh)
# DO NOT COMMIT THIS FILE
DATABASE_URL=$TEST_DATABASE_URL
REDIS_URL=$REDIS_URL
JWT_SECRET_KEY=$JWT_SECRET_KEY
TESTING=true
DEBUG=false
EOF

echo "✅ Test environment configured!"
echo ""
echo "📊 Configuration Summary:"
echo "   - Database: ${TEST_DATABASE_URL:0:30}..."
echo "   - Redis: $REDIS_URL"
echo "   - JWT configured: $([ -n "$JWT_SECRET_KEY" ] && echo "Yes" || echo "No")"
echo "   - OpenAI configured: $([ -n "$OPENAI_API_KEY" ] && echo "Yes" || echo "No")"
echo ""
echo "🚀 You can now run tests with:"
echo "   pytest"
echo "   pytest --cov=. --cov-report=html"
echo ""
echo "⚠️  Remember: .env.test is temporary - do not commit it!"