version: '3.9'

services:
  neo4j:
    image: neo4j:5.26.10-community
    container_name: ruleiq-neo4j  # Use existing ruleIQ Neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/please_change
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_memory_pagecache_size: 512m
      # Enable APOC and other plugins if needed
      NEO4J_PLUGINS: '["apoc"]'
      # Security settings for development
      NEO4J_dbms_security_procedures_unrestricted: "*"
      NEO4J_dbms_security_procedures_allowlist: "*"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - golden_dataset_network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  golden_dataset_network:
    driver: bridge