version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_URL=${DATABASE_URL}  # Use Neon database URL from .env
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - compliancegpt-network

  celery_worker:
    build: .
    command: celery -A celery_app worker --loglevel=debug --concurrency=2 --pool=solo --traceback --queues=evidence,compliance,notifications,reports
    environment:
      - ENV=development
      - DATABASE_URL=${DATABASE_URL}  # Use Neon database URL from .env
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:$PYTHONPATH
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - compliancegpt-network
    healthcheck:
      test: ["CMD", "celery", "-A", "celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_beat:
    build: .
    command: celery -A celery_app beat --loglevel=debug
    environment:
      - ENV=development
      - DATABASE_URL=${DATABASE_URL}  # Use Neon database URL from .env
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:$PYTHONPATH
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - compliancegpt-network

  # Redis is still needed for caching and Celery task queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - compliancegpt-network

volumes:
  redis_data:

networks:
  compliancegpt-network:
    driver: bridge