"""Add RBAC system tables

Revision ID: 52b4f203af3a
Revises: add_check_constraints_data_integrity
Create Date: 2025-07-25 03:29:04.463516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b4f203af3a'
down_revision = 'add_check_constraints_data_integrity'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###