"""Add RBAC tables for role-based access control

from __future__ import annotations

Revision ID: b8a4b53d1de0
Revises: 52b4f203af3a
Create Date: 2025-07-25 03:31:18.237271

"""

# revision identifiers, used by Alembic.
revision = "b8a4b53d1de0"
down_revision = "52b4f203af3a"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
