# ruleIQ Privacy and PII Detection Policy (skeleton)
# This file defines detectors, redaction strategies, and per-tenant overrides.
# Wire this via SanitizeRequest/SanitizeResponse middleware.
# NOTE: Keep secrets (vault URI/keys) in environment variables, not in this file.

version: 1
defaults:
  detectors:
    regex:
      # Basic patterns (enable/disable by type)
      email:
        enabled: true
        pattern: '(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}'
        flags: ['IGNORECASE']
      phone:
        enabled: true
        pattern: '(?:(?:\\+|00)\\d{1,3}[\\s-]?)?\\(?\\d{2,4}\\)?[\\s-]?\\d{3,4}[\\s-]?\\d{3,4}'
      national_id:
        enabled: true
        # Example UK NI number; add more country-specifics under overrides
        pattern: '(?i)\\b(?!BG|GB|NK|NT|TN|ZZ)[A-CEGHJ-PR-TW-Z]{2}\\d{6}[A-D]\\b'
      ip_address:
        enabled: true
        pattern: '\\b(?:(?:2(?:5[0-5]|[0-4]\\d))|(?:1?\\d?\\d))(?:\\.(?:(?:2(?:5[0-5]|[0-4]\\d))|(?:1?\\d?\\d))){3}\\b'
      credit_card:
        enabled: true
        pattern: '\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b'

    custom_regex:
      # Add any tenant-specific patterns here
      - name: internal_ticket
        enabled: false
        pattern: '\\b[A-Z]{2,4}-\\d{3,6}\\b'

    ml_ner:
      enabled: true
      provider: spacy # spacy | presidio
      model: en_core_web_trf
      entities:
        # Common PII entities
        - PERSON
        - ORG
        - GPE
        - LOC
        - NORP
        - DATE
      thresholds:
        PERSON: 0.80
        ORG: 0.85
        GPE: 0.80
        LOC: 0.80
        NORP: 0.85
        DATE: 0.80

  redaction:
    strategy: tag # tag | mask | remove | vault
    tag_format: "[REDACTED:%TYPE%]"
    mask_char: "*"
    preserve_length: false
    # Vault-based reversible redaction (store mappings)
    reversible_vault:
      enabled: false
      provider: "hashicorp" # or "aws-kms", "gcp-kms"
      # vault_uri is supplied via env var: PRIVACY_VAULT_URI
      mapping_ttl_seconds: 2592000 # 30 days

  bypass:
    # Roles that may bypass PII blocks (with justification)
    allowed_roles:
      - compliance_officer
      - admin
    require_justification: true
    log_to_safety_audit: true

  post_llm_scrub:
    enabled: true
    detectors: ["regex", "ml_ner"] # Re-apply after LLM output
    annotate_safety_decision: true

  performance:
    enable_short_circuit: true # stop after first high-confidence match
    max_runtime_ms: 40
    batch_mode: true

  retention:
    default_days: 365
    auto_purge_enabled: true

overrides:
  # Per-tenant/region overrides
  tenants:
    # Example tenant override
    acme_corp:
      detectors:
        ml_ner:
          model: en_core_web_trf
          thresholds:
            PERSON: 0.88
            ORG: 0.90
      redaction:
        strategy: vault
        reversible_vault:
          enabled: true
      bypass:
        allowed_roles: [compliance_officer] # admin must still justify
      retention:
        default_days: 730
  regions:
    eu:
      data_residency: strict
      ml_ner:
        enabled: true
        model: en_core_web_trf
    us:
      ml_ner:
        enabled: true
        model: en_core_web_trf

testing:
  # Corpus-driven validation thresholds
  precision_target: 0.98
  recall_target: 0.95
  golden_suite_paths:
    - tests/data/pii_corpus/*.txt
  zero_egress_required: true