name: Deploy Frontend to Production

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # First, ensure the quality gates pass
  quality-check:
    uses: ./.github/workflows/quality-gates.yml

  # If quality gates pass, deploy to production after manual approval
  deploy-production:
    needs: quality-check
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ruleiq.com # Placeholder URL

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Validate Environment Variables
        run: node scripts/validate-env.mjs
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.PRODUCTION_API_URL }}

      - name: Build application
        run: pnpm build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.PRODUCTION_API_URL }}

      - name: Deploy to Production Environment
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          echo "🚀 Deploying to PRODUCTION..."
          npx vercel-cli pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel-cli build --prod --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel-cli deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
