# Prometheus alerting rules for AI Assessment Freemium Strategy

groups:
  - name: freemium.api.alerts
    rules:
      # High error rate on freemium endpoints
      - alert: FreemiumHighErrorRate
        expr: rate(http_requests_total{job="ruleiq-freemium-api",path=~"/api/v1/freemium/.*",status=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: freemium-api
        annotations:
          summary: "High error rate on freemium endpoints"
          description: "Freemium API error rate is {{ $value }} errors per second, above 5% threshold"

      # Slow response times on freemium endpoints
      - alert: FreemiumSlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="ruleiq-freemium-api",path=~"/api/v1/freemium/.*"}[5m])) > 2.0
        for: 3m
        labels:
          severity: warning
          service: freemium-api
        annotations:
          summary: "Slow response times on freemium endpoints"
          description: "95th percentile response time is {{ $value }}s, above 2s threshold"

      # High rate limiting on freemium endpoints
      - alert: FreemiumHighRateLimiting
        expr: rate(http_requests_total{job="ruleiq-freemium-api",path=~"/api/v1/freemium/.*",status="429"}[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          service: freemium-api
        annotations:
          summary: "High rate limiting on freemium endpoints"
          description: "Rate limiting is affecting {{ $value }} requests per second"

      # Email capture endpoint issues
      - alert: EmailCaptureEndpointDown
        expr: up{job="ruleiq-freemium-api"} == 0 or rate(http_requests_total{job="ruleiq-freemium-api",path="/api/v1/freemium/capture-email",status=~"2.."}[5m]) == 0
        for: 1m
        labels:
          severity: critical
          service: freemium-api
          endpoint: capture-email
        annotations:
          summary: "Email capture endpoint is not responding"
          description: "Critical freemium email capture endpoint is down or not receiving successful requests"

  - name: freemium.ai.alerts
    rules:
      # AI service failure rate
      - alert: FreemiumAIServiceFailure
        expr: rate(ai_requests_total{service="freemium",status="error"}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: ai-service
        annotations:
          summary: "High AI service failure rate for freemium"
          description: "AI service failure rate is {{ $value }} failures per second"

      # AI response time degradation
      - alert: FreemiumAISlowResponse
        expr: histogram_quantile(0.90, rate(ai_request_duration_seconds_bucket{service="freemium"}[5m])) > 10.0
        for: 3m
        labels:
          severity: warning
          service: ai-service
        annotations:
          summary: "Slow AI response times for freemium assessments"
          description: "90th percentile AI response time is {{ $value }}s, above 10s threshold"

      # AI cost threshold exceeded
      - alert: FreemiumAICostThreshold
        expr: ai_cost_total{service="freemium"} > 100
        for: 0m
        labels:
          severity: warning
          service: ai-service
        annotations:
          summary: "Daily AI cost threshold exceeded for freemium"
          description: "Freemium AI costs have reached ${{ $value }}, above $100 daily threshold"

  - name: freemium.business.alerts
    rules:
      # Low conversion rate
      - alert: FreemiumLowConversionRate
        expr: (rate(freemium_conversions_total[1h]) / rate(freemium_assessments_completed_total[1h])) < 0.05
        for: 15m
        labels:
          severity: warning
          service: business-metrics
        annotations:
          summary: "Low freemium conversion rate"
          description: "Conversion rate is {{ $value | humanizePercentage }}, below 5% threshold"

      # High assessment abandonment rate
      - alert: FreemiumHighAbandonmentRate
        expr: (rate(freemium_assessments_started_total[1h]) - rate(freemium_assessments_completed_total[1h])) / rate(freemium_assessments_started_total[1h]) > 0.7
        for: 10m
        labels:
          severity: warning
          service: business-metrics
        annotations:
          summary: "High assessment abandonment rate"
          description: "Assessment abandonment rate is {{ $value | humanizePercentage }}, above 70% threshold"

      # Unusual traffic spike
      - alert: FreemiumTrafficSpike
        expr: rate(http_requests_total{job="ruleiq-freemium-api",path=~"/api/v1/freemium/.*"}[5m]) > 10
        for: 2m
        labels:
          severity: info
          service: freemium-api
        annotations:
          summary: "Unusual traffic spike on freemium endpoints"
          description: "Request rate is {{ $value }} requests per second, significantly above normal"

  - name: freemium.infrastructure.alerts
    rules:
      # Redis connection issues
      - alert: FreemiumRedisDown
        expr: redis_up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis instance is not responding, affecting freemium caching"

      # High Redis memory usage
      - alert: FreemiumRedisHighMemory
        expr: redis_memory_used_bytes{job="redis"} / redis_memory_max_bytes{job="redis"} > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }}, above 90% threshold"

      # Celery worker issues
      - alert: FreemiumCeleryWorkerDown
        expr: celery_workers_active{queue="freemium"} == 0
        for: 2m
        labels:
          severity: critical
          service: celery
        annotations:
          summary: "No active Celery workers for freemium queue"
          description: "Freemium background tasks are not being processed"

      # High queue backlog
      - alert: FreemiumHighQueueBacklog
        expr: celery_queue_length{queue="freemium"} > 100
        for: 5m
        labels:
          severity: warning
          service: celery
        annotations:
          summary: "High freemium queue backlog"
          description: "Freemium queue has {{ $value }} pending tasks"

  - name: freemium.security.alerts
    rules:
      # Suspicious request patterns
      - alert: FreemiumSuspiciousActivity
        expr: rate(http_requests_total{job="ruleiq-freemium-api",path="/api/v1/freemium/capture-email",status="400"}[5m]) > 1
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Suspicious activity on email capture endpoint"
          description: "High rate of 400 errors suggests potential bot or attack activity"

      # Multiple failed authentication attempts
      - alert: FreemiumBruteForceAttempt
        expr: rate(http_requests_total{job="ruleiq-freemium-api",status="401"}[5m]) > 0.5
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Potential brute force attack on freemium endpoints"
          description: "High rate of 401 errors: {{ $value }} failed attempts per second"