version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: ruleiq-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compliance_test
    ports:
      - "5433:5432"  # Using 5433 to avoid conflicts with local PostgreSQL
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  # Optional: PgAdmin for debugging
  pgadmin-test:
    image: dpage/pgadmin4:latest
    container_name: ruleiq-pgadmin-test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - test-network
    profiles:
      - debug  # Only starts when --profile debug is used

volumes:
  postgres_test_data:
    driver: local

networks:
  test-network:
    driver: bridge